# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database:
            entity:
                class: AppBundle:User
                property: googleAccount

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        app:
            provider: database
            anonymous: ~
            pattern: ^/
            logout:
                path: logout
                target: login
                invalidate_session: true

        main:
            anonymous: ~

    access_control:
        login:
            path: ^/login
            role: IS_AUTHENTICATED_ANONYMOUSLY

        login:
            path: ^/register
            role: IS_AUTHENTICATED_ANONYMOUSLY
        user:
            path: ^/
            role: ROLE_USER
