# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        AppBundle\Entity\User:
            algorithm: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        app:
            provider: database
            anonymous: ~
            pattern: ^/
            switch_user: true
            logout:
                path: logout
                target: login
                invalidate_session: true

        main:
            anonymous: ~

    access_control:
        account:
            path: ^/login
            role: IS_AUTHENTICATED_ANONYMOUSLY
        refresh:
            path: ^/refresh
            role: ROLE_USER
        refresh:
            path: ^/group
            role: ROLE_USER
        edit:
            path: ^/edit
            role: ROLE_ADMIN
        notification:
            path: ^/notification
            role: ROLE_USER
