# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    player:
        class: AppBundle\Service\Player
        arguments: ["@doctrine.orm.entity_manager"]
    local:
        class: AppBundle\Service\Locale
        arguments: ["@service_container", "%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
